# -*- coding: utf-8 -*-
"""
clear code le platformer complet, partie 2 sur le visual level editor, game_data
"""

#attention, a changer suivant les niveaux 
level_1 = {'terrain': '../../design/niveau1/map/level_1_map_terrain.csv',
           'item': '../../design/niveau1/map/level_1_map_items.csv',
           'enemies': '../../design/niveau1/map/level_1_map_enemies.csv',
           'constraints': '../../design/niveau1/map/level_1_map_constraints.csv',
           'player':'../../design/niveau1/map/level_1_map_player.csv',
           'node_pos': (140,400),
           'unlock': 2,
           'node_graphics': '../../design/overworld/1.png',
           'animation_speed': 0.15,
           'status': 'stand',
           'speed': 8,
           'gravity': 0.8,
           'jump_speed': -16,
           'items': ['arc', 'lyre', 'montre'],
           'rotation': 0,
           'monsters': ['../../design/niveau1/monster/cyclope_w', '../../design/niveau1/monster/satyr', '../../design/niveau1/monster/cow_1', '../../design/niveau1/monster/cow_2'],
           'dieu': ['../../design/niveau1/apollon.png'], 
           'place_dieu': [0.6, 0.1, 0.3, 0.6],
           'bon_obj': 'lyre',
           'mauv_obj1': 'arc',
           'mauv_obj2': 'montre',
           'dialogue_all': ["Apollon – Oh non pas toi ! Que fais tu ici mon frère ? Tu es encore venu me voler mes vaches ?",
                           "Hermes – Non, je suis venu te demander de la laine.",
                           "Apollon – Pourquoi me demande-tu cela ? Tu ne peux pas demander à quelqu'un d'autre ? Je ne suis pas un mouton !",
                           "Hermes – Je veux construire un trône, pour devenir le douzième dieu de l'Olympe.",
                           "Apollon – Mhooo c'est mignon, tu veux devenir comme ton incroyable et sublime grand frère petit Hermès ? Si tu veux vraiment cette laine il va falloir me donner quelque chose en échange."],
           'dialogue_bon_obj': ["Hermes – J'ai retrouvé ta lyre ! *il joue un morceau avec la lyre* Si tu la veux, il va falloir me donner la laine.",
                           "Apollon – Ma lyre ! Je l'avais perdu. C'est d'accord, marché conclu, voici la laine.",
                           "Apollon – D'ailleurs, tu as entendu la nouvelle ? Le roi de la poiscaille a perdu sa fourchette. Hahaha. Quel idiot !",
                           "*victoire, niveau suivant* *appuyez sur 'e' pour sortir*"],
           'dialogue_mauv_obj1': ["Hermes – Je peux t'échanger un arc.", 
                              "Apollon – Mais je n'en ai rien à faire de ça. Tu n'as pas autre chose ?",
                              "Hermes – Non je n'a rien d'autre.",
                              "Apollon – Alors va retrouver ma lyre, je l'ai perdu il y a quelques jours. Et si tu la retrouves, je te donnerai ce que tu veux.",
                              "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_mauv_obj2': ["Hermes – Je peux t'échanger une montre.", 
                              "Apollon – Mais je n'en ai rien à faire de ça. Tu n'as pas autre chose ?",
                              "Hermes – Non je n'a rien d'autre.",
                              "Apollon – Alors va retrouver ma lyre, je l'ai perdu il y a quelques jours. Et si tu la retrouves, je te donnerai ce que tu veux.",
                              "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_no': ["Hermes – Je n'ai rien à t'échanger.",
                           "Apollon – Alors va retrouver ma lyre, je l'ai perdu il y a quelques jours. Et si tu la retrouves, je te donnerai ce que tu veux.",
                           "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_recom': ["Apollon – Alors tu l'as trouvé ?"]
           } #design/

level_2 = {'terrain': '../../design/niveau2/map/level_2_map_terrain.csv',
           'item': '../../design/niveau2/map/level_2_map_items.csv',
           'enemies': '../../design/niveau2/map/level_2_map_enemies.csv',
           'constraints': '../../design/niveau2/map/level_2_map_constraints.csv',
           'player':'../../design/niveau2/map/level_2_map_player.csv',
           'node_pos': (330,230),
           'unlock': 3,
           'node_graphics': '../../design/overworld/2.png',
           'animation_speed': 0.05,
           'status': 'swim',
           'speed': 4,
           'gravity': 0.04,
           'jump_speed': -2,
           'items': ['fourchette', 'peanut butter', 'trident'],
           'rotation': -90,
           'monsters': ['../../design/niveau2/monster/fish', '../../design/niveau2/monster/mermaid', '../../design/niveau2/monster/poulpe'],
           'dieu': ['../../design/niveau2/poseidon.png'], 
           'place_dieu': [0.55, 0.13, 0.35, 0.6],
           'bon_obj': 'trident',
           'mauv_obj1': 'fourchette',
           'mauv_obj2': 'peanut butter',
           'dialogue_all': ["Poséidon – Hermès ? Tu es encore là ? Je croyais qu'ils t'avaient enfin remplacé par les emails.",
                           "Hermes – *pas content* Je suis venu te demander des pierres précieuses.",
                           "Poséidon – Des pierres précieuses ? Pourquoi en voudrais-tu ? Si c'est Hécate qui t'envoie, dit lui que je lui en ai donné bien assez et qu'elle ne vienne plus m'ennuyer avec ça.",
                           "Hermes – Personne ne m'envoie, les pierres sont pour moi. Je veux construire un trône, pour devenir le douzième dieu de l'Olympe.",
                           "Poséidon – Hahaha !! Tu es bien ambitieux mon neveux. Et qu'est-ce qu'il te fait croire que je vais te donner mes précieuses pierres ?"],
           'dialogue_bon_obj': ["Hermes – J'ai trouvé ton trident sur le chemin jusqu'ici. Je te propose de l'échanger contre les pierres.",
                            "Poséidon – Mon trident ! Tu as de la chance dieu de la ruse. Marché conclu, voilà les pierres.",
                           "Poséidon – Un conseil pour ta quête, ne traine pas trop sous terre. Le dieu des morts ne peut plus cacher sa tête d'enterrement et il a l'air contrarié.",
                           "*victoire, niveau suivant* *appuyez sur 'e' pour sortir*"],
           'dialogue_mauv_obj1': ["Hermes – J'ai une fourchette.", 
                              "Poséidon – Sérieusement ? Tu penses vraiment que c'est équivalent à mes pierres ?",
                              "Hermes – Je n'a rien d'autre à t'échanger.",
                              "Poséidon – Ha ha ha j'en était sur ! Si tu veux mes pierres, trouve donc mon trident, je l'ai perdu quelque part dans l'océan.",
                              "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_mauv_obj2': ["Hermes – J'ai du beurre de cacahuète.", 
                              "Poséidon – Sérieusement ? Tu penses vraiment que c'est équivalent à mes pierres ?",
                              "Hermes – Je n'a rien d'autre à t'échanger.",
                              "Poséidon – Ha ha ha j'en était sur ! Si tu veux mes pierres, trouve donc mon trident, je l'ai perdu quelque part dans l'océan.",
                              "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_no': ["Hermes – Je n'ai rien à t'échanger.",
                           "Poséidon – Ha ha ha j'en était sur ! Si tu veux mes pierres, trouve donc mon trident, je l'ai perdu quelque part dans l'océan.",
                           "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_recom': ["Poséidon – Tu en a mis du temps."]
           }

level_3 = {'terrain': '../../design/niveau3/map/level_3_map_terrain.csv',
           'item': '../../design/niveau3/map/level_3_map_items.csv',
           'enemies': '../../design/niveau3/map/level_3_map_enemies.csv',
           'constraints': '../../design/niveau3/map/level_3_map_constraints.csv',
           'player':'../../design/niveau3/map/level_3_map_player.csv',
           'node_pos': (510,610),
           'unlock': 4,
           'node_graphics': '../../design/overworld/3.png',
           'animation_speed': 0.15,
           'status': 'stand',
           'speed': 8,
           'gravity': - 0.8,
           'jump_speed': 16,
           'items': ['livre', 'casque', 'potion'],
           'rotation': -180,
           'monsters': ['../../design/niveau3/monster/cerber', '../../design/niveau3/monster/ghost', '../../design/niveau3/monster/skeleton'],
           'dieu': ['../../design/niveau3/hades.png'], 
           'place_dieu': [0.55, 0.13, 0.35, 0.6],
           'bon_obj': 'casque',
           'mauv_obj1': 'livre',
           'mauv_obj2': 'potion',
           'dialogue_all': ["Hadès – Bonjour Hermès. Que me vaut cette irruption dans mon royaume ? Amènes-tu une âme aux Enfers ?",
                           "Hermès – Non, pas aujourd’hui. J'ai besoin de ton aide dieu de la richesse. J'ai besoin d'or.",
                           "Hadès – Hmmm... Intéressant. Et pourquoi veux-tu de l'or ?",
                           "Hermès – Je veux construire un trône, pour devenir le douzième dieu de l'Olympe.",
                           "Hadès – Très intéressant. Je te souhaite bon courage. Mais tu connais les lois divines Hermès, je ne te donnerai ce que tu veux uniquement si tu as quelque chose à m'échanger."],
           'dialogue_bon_obj': ["Hermès – J'ai trouvé ton casque, la kunée. Je te propose un échange, l'or contre le casque.",
                              "Hadès – Très bien. Marché conclu. Voilà tout l'or dont tu as besoin pour ton trône.",
                              "Hadès – Si tu peux me rendre un service, va donc rendre visite au forgeron de l'Olympe, il se sent bien seul.",
                              "*victoire, niveau suivant*"],
           'dialogue_mauv_obj1': ["Hermes – J' ai trouvé un livre.", 
                              "Hadès – Cet objet ne m'intéresse pas. Pas contre de l'or en tous cas.",
                              "Hermes – Je n'ai rien trouvé d'autre pour l'échange.",
                              "Hadès – Alors c'est moi qui te propose un marché. Je te donnerai de l'or si tu retrouves mon casque, la kunée. Elle est quelque part aux enfers. Bon courage.",
                              "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_mauv_obj2': ["Hermes – J' ai trouvé une potion.", 
                              "Hadès – Cet objet ne m'intéresse pas. Pas contre de l'or en tous cas.",
                              "Hermes – Je n'ai rien trouvé d'autre pour l'échange.",
                              "Hadès – Alors c'est moi qui te propose un marché. Je te donnerai de l'or si tu retrouves mon casque, la kunée. Elle est quelque part aux enfers. Bon courage.",
                              "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_no': ["Hermès – Je n'ai rien à t'échanger.",
                           "Hadès – Alors c'est moi qui te propose un marché. Je te donnerai de l'or si tu retrouves mon casque, la kunée. Elle est quelque part aux enfers. Bon courage.",
                           "*défaite, retour au début du niveau* *appuyez sur 'e' pour sortir*"],
           'dialogue_recom': ["Hadès – Déjà de retour à ce que je vois."]
           }
 
level_4 = {'terrain': '../../design/niveau1/map/level_1_map_terrain.csv',
           'item': '../../design/niveau1/map/level_1_map_items.csv',
           'enemies': '../../design/niveau1/map/level_1_map_enemies.csv',
           'constraints': '../../design/niveau1/map/level_1_map_constraints.csv',
           'player':'../../design/niveau1/map/level_1_map_player.csv',
           'node_pos': (640,350),
           'unlock': 5,
           'node_graphics': '../../design/overworld/4.png',
           'animation_speed': 0.15,
           'status': 'stand',
           'speed': 8,
           'gravity': 0.8,
           'jump_speed': -16,
           'items' : ['ciseaux', 'amour', 'pelle'],
           'rotation':0,
           'monsters': ['../../design/niveau4/monster/bat', '../../design/niveau4/monster/fire', '../../design/niveau4/monster/stalactite']
           }

level_5 = {'terrain': '../../design/niveau1/map/level_1_map_terrain.csv',
           'item': '../../design/niveau1/map/level_1_map_items.csv',
           'enemies': '../../design/niveau1/map/level_1_map_enemies.csv',
           'constraints': '../../design/niveau1/map/level_1_map_constraints.csv',
           'player':'../../design/niveau1/map/level_1_map_player.csv',
           'node_pos': (910,210),
           'unlock': 5,
           'node_graphics': '../../design/overworld/5.png',
           'animation_speed': 0.15,
           'status': 'stand',
           'speed': 8,
           'gravity': 0.8,
           'jump_speed': -16,
            'items' : [None, None, None], #y'a pas d'item au niveau 5 enfaite,
            'rotation':0,
            'monsters': ['../../design/niveau1/monster/cyclope_w', '../../design/niveau1/monster/satyr', '../../design/niveau1/monster/cow_1', '../../design/niveau1/monster/cow_2']
           }

levels = {
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5}














